### ISSUE TITLE
Call to `window.addEventListener` fails when using sdk in react-native

### ISSUE THREAD

**Issue by ottodevs** [LIT-Protocol/lit-js-sdk#22]
It should be nice if a proper condition is added to this line so it does not fail when using in react-native, since `window.addEventListener` is not available in react-native, but it is being called without any checks from `listenForFrameParentMessages()` function within that condition...
https://github.com/LIT-Protocol/lit-js-sdk/blob/f0096db3c2ee2198abcfb1dac588aed2a5715891/src/index.js#L10

So it should be like

```js
if (typeof window !== "undefined" && typeof window.addEventListener !== "undefined") {
```

**Comment by glitch003** [comment]
Hey, thanks for pointing this out.  Are you using the SDK in react native successfully?  

Would love to chat about using this SDK on RN.  We got it working last week and created a custom package for it: https://www.npmjs.com/package/lit-js-sdk-no-wasm

Here's an example app we got working: https://github.com/LIT-Protocol/react-native-example

But the problem is that it's super slow and also blocks the RN UI while it's processing.  This may be because we couldn't run WASM in RN so we transpiled the WASM to JS which works but is much slower than native WASM.  Any ideas on how to fix this?  Even if we could just run this on a background thread and not block the RN UI, it would be a big improvement.

**Comment by ottodevs** [comment]
Thanks for the answer, we are still working into the core implementation using Lit protocol, it seems that Orbis sdk team also did some workarounds to have it working for their mobile app.

Let's keep in touch over discord, I posted there in #tech-support linking this issue

**Comment by glitch003** [comment]
Did you get this resolved?
